<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SenpaiOptions {
	private $senpai_options_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'senpai_options_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'senpai_options_page_init' ) );
	}

	public function senpai_options_add_plugin_page() {
		add_menu_page(
			'', // page_title
			'senpai options', // menu_title
			'manage_options', // capability
			'senpai-options', // menu_slug
			array( $this, 'senpai_options_create_admin_page' ), // function
			'dashicons-pressthis', // icon_url
			3 // position
		);
	}

	public function senpai_options_create_admin_page() {
        $this->senpai_options_options = get_option( 'senpai_options_option_name' ); 
        
        ob_start();
        include('admin-view.php');
        $content = ob_get_contents();
        ob_end_clean();
        ?>

		<div class="wrap">
			<h2>senpai options</h2>
			<p>hello</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'senpai_options_option_group' );
					do_settings_sections( 'senpai-options-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function senpai_options_page_init() {
		register_setting(
			'senpai_options_option_group', // option_group
			'senpai_options_option_name', // option_name
			array( $this, 'senpai_options_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'senpai_options_setting_section', // id
			'Settings', // title
			array( $this, 'senpai_options_section_info' ), // callback
			'senpai-options-admin' // page
		);

		add_settings_field(
			'test_0', // id
			'test', // title
			array( $this, 'test_0_callback' ), // callback
			'senpai-options-admin', // page
			'senpai_options_setting_section' // section
		);
	}

	public function senpai_options_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['test_0'] ) ) {
			$sanitary_values['test_0'] = sanitize_text_field( $input['test_0'] );
		}

		return $sanitary_values;
	}

	public function senpai_options_section_info() {
		
	}

	public function test_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="senpai_options_option_name[test_0]" id="test_0" value="%s">',
			isset( $this->senpai_options_options['test_0'] ) ? esc_attr( $this->senpai_options_options['test_0']) : ''
		);
	}

}
if ( is_admin() )
	$senpai_options = new SenpaiOptions();

/* 
 * Retrieve this value with:
 * $senpai_options_options = get_option( 'senpai_options_option_name' ); // Array of All Options
 * $test_0 = $senpai_options_options['test_0']; // test
 */

 /**
 * Enqueue a script in the WordPress admin on edit.php.
 *
 * @param int $hook Hook suffix for the current admin page.
 */
function senpai_selectively_enqueue_admin_script( $hook ) {
    error_log(print_r($hook,1));
    if ( 'toplevel_page_senpai-options' != $hook ) {
        return;
    }
    wp_enqueue_script( 'senpai_admin_script', get_template_directory_uri() . '/admin/admin.js', array('jquery'), '1.0' );
    wp_enqueue_style( 'senpai_admin_css_bs4', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', false, '1.0.0','all');

    wp_enqueue_style( 'senpai_admin_css', get_template_directory_uri() . '/admin/admin.css', false, '1.0.0','all');
}
add_action( 'admin_enqueue_scripts', 'senpai_selectively_enqueue_admin_script' );
